function image_analysis_agg_AR_V3_XFwithoutCellsClassification(route, myFolder)

[X,~] = imread(route);
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 23-Nov-2023
%----------------------------------------------------
% Convertir la imagen a escala de grises
reductionFactor = 0.67;

% Get the size of the original image
originalSize = size(X);

% Calculate the new size based on the reduction factor
newSize = floor(originalSize(1:2) * reductionFactor);

% Calculate the amount to be cropped from each side
cropAmount = floor((originalSize(1:2) - newSize) / 2);

% Calculate the starting point for cropping
startPoint = [cropAmount(1) + 1, cropAmount(2) + 1, 1];

% Crop the image
croppedImage = X(startPoint(1):(startPoint(1) + newSize(1) - 1), ...
                 startPoint(2):(startPoint(2) + newSize(2) - 1), :);

X = croppedImage;
BW = imbinarize(im2gray(X), 'adaptive', 'Sensitivity', 0.700000, 'ForegroundPolarity', 'bright');

% Invert mask
BW = imcomplement(BW);

% Fill holes
BW = imfill(BW, 'holes');
% Clear borders
BW = imclearborder(BW);
% Create masked image.


BW_out = bwpropfilt(BW,'Area',[1000 + eps(1000), Inf]);
propsbw = regionprops(BW_out, {'Area', 'Centroid', 'Perimeter', 'Circularity', 'Eccentricity', 'Solidity','MinorAxisLength','MajorAxisLength'});

propsbw_cleaned = struct('Area', [], 'Centroid', [], 'Perimeter', [], 'Circularity', [], 'Eccentricity', [],  'Solidity',[], 'MinorAxisLength',[], 'MajorAxisLength',[]);


% Extract the base name of the original image without the file extension
[~, baseName, ~] = fileparts(route);

% Split the baseName into parts using underscores
nameParts = strsplit(baseName, '_');

% Extract dilution and time information
dilution = str2double(nameParts{end - 1});  % Assuming dilution is the second-to-last part
time = str2double(nameParts{end});  % Assuming time is the last part


% Use imwrite to save the binary image with the new name
% Save the modified image with area values
newImageName = strcat(baseName, '_area.tif');  % Choose an appropriate image format
% Save the binary image with areas labeled
imwrite(BW_out, fullfile(myFolder, newImageName));


% Add the rows with Area > 300 to properties_cleaned
for i = 1:length(propsbw)
    if propsbw(i).Area > 1000
        propsbw_cleaned(end+1) = propsbw(i);
    end
end

propsbw_cleaned(1) = [];

enumerationColumn = cell(length(propsbw_cleaned), 1);

for i = 1:length(propsbw_cleaned)
    propsbw_cleaned(i).Concentration = [];
    propsbw_cleaned(i).Time = [];
    propsbw_cleaned(i).Enumeration = [];
    enumerationColumn{i} = num2str(i);
end

for i = 1:length(propsbw_cleaned)
    propsbw_cleaned(i).Concentration = dilution;
    propsbw_cleaned(i).Time = time;
end

% Remove empty cells from enumerationColumn
enumerationColumn = enumerationColumn(~cellfun('isempty', enumerationColumn));

% Assign enumerationColumn to propsbw_cleaned
[propsbw_cleaned.Enumeration] = enumerationColumn{:};

% Extract the base name of the original image without the file extension
[~, baseName, ~] = fileparts(route);

% Create the new name for the MAT file by appending "_results.mat"
FileName = fullfile(myFolder, [baseName, '_results.mat']);
FileName_csv = fullfile(myFolder, [baseName, '_results.csv']);
writetable(struct2table(propsbw_cleaned), FileName_csv,'delimiter',',');
% Write the structure to a MAT file using save
save(FileName, 'propsbw_cleaned');

end
